### ISSUE TITLE
Lagrangian Paraview Binary output partially broken

### ISSUE THREAD

**Issue by Robadob** [gnomeCreative/HYBIRD#24]
Current implementation always outputs `dynVisc` header, but only sometimes the data.

**Header** (middle 2 lines not wrapped in `if`)

https://github.com/gnomeCreative/HYBIRD/blob/d79d14cd93c81afcf27aac57a6d9b5e1ed432cfa/src/IO.cpp#L1609-L1612

**Data**

https://github.com/gnomeCreative/HYBIRD/blob/d79d14cd93c81afcf27aac57a6d9b5e1ed432cfa/src/IO.cpp#L1673-L1681

When the data buffer is not output, this led to a ParaView load error.

> Cannot read point data array "mass" from PointData piece 0. The data array in the element may be too short.

Presumed to be a case of offsets becoming out of place and something getting misread.
However, if that condition is added to the header instead it changes to.

> Cannot read cell connectivity from Cells in piece 0 because the "offsets" array is not monotonically increasing or starts with a value other than 0.

I've had a quick look, but can't find this second bug (the offset calculated for header, and at time of write appear to match), unclear how this ever worked given `mass` should have same length/type as `dynVisc` so it shouldn't have failed there anyway.

<details>
<summary>Input files to reproduce</summary>

`testgeometry.cfg`

```cfg
# CONFIGURATION FILE FOR HYBIRD

# SOLVER SWITCHERS
demSolver               = 0         #
lbSolver                = 1        #
freeSurfaceSolver       = 0         #
forceFieldSolver        = 1         #
staticFrictionSolver    = 0         #

# PROBLEM NAME
problemName             = testWallYML	    #
problemFile 			= testWall.yml 	# geometry file name

# OUTPUT
screenExpTime           = 0.1		    # print data on screen every x time (0 for deactivated)
fluidExpTime            = 1.0		    # write vtk file every x time (0 for deactivated)
#fluidLagrangianFormat   = ASCII
fluidLagrangianExpTime  = 1.0		    # write Lagrangian vtk file every x time (0 for deactivated)
partExpTime             = 0			    # write vtk file every x time (0 for deactivated)
partRecycleExpTime      = 0		    # write particle recycle file every x time (0 for deactivated)
fluidRecycleExpTime     = 0		    # write particle recycle file every x simulation time units (0 for deactivated)
fluid2DExpTime          = 0         # write a 2D topographycal file every x time. Maximum values are updated every screenExpTime
objectExpTime           = 0		    # write object file every x time units (0 for deactivated)
singleObjects           = ''        # objects to track 

# TIME INTEGRATION
demInitialRepeat        = 0			#
lbmInitialRepeat        = 0			#
maximumTimeSteps        = 0			# run until this number of timesteps is reached (0 for infinite)
maxTime                 = 20.0		# run until the time variable has reached this value (0 for infinite) 50
fluidTimeStep           = 0	    # time 1.0e-4
multiStep               = 0			# number of DEM steps between LBM steps. If 0, it is determined inside the program
criticalRatio           = 0.002 	    # ratio between DEM time step and estimated duration of contacts (only if multiStep=0)

# DOMAIN AND FORCING
domainSizeX             = 0.2		# length
domainSizeY             = 0.1     	# length
domainSizeZ             = 2.0		# length
forceX                  = 1.0	    # length/time^2
forceY                  = 0.0		# length/time^2
forceZ                  = 0.0	    # length/time^2
boundary0               = periodic		# negative X
boundary1               = periodic		# positive X
boundary2               = periodic		# negative Y
boundary3               = periodic		# positive Y
boundary4               = stat_wall		# negative Z
boundary5               = stat_wall		# positive Z

# LBM PARAMETERS
latticeSpacing          = 0.01		    # length
fluidDensity            = 1.0	    # mass/length^3
minTau                  = 0.5005      # for limiting turbulence in some non-Newtonian models
maxTau                  = 1.0       # for theoretical stability
TRTsolver               = false     # two-relaxation-time solver
imposeFluidVolume       = false     # to fix mass at a certain level, mass will be added/removed to reach it
imposedFluidVolume      = 0.0       # mass to impose if the above is true
restartFluid            = false     #
fluidRestartFile        = ./	    #
applyTopography         = false     #
topographyFile          = ./        # need to fully contain the domain in direction x and y
fluidFromTopography     = false     # reads level from fourth column in topography file
translateTopographyX    = 0.0       # length
translateTopographyY    = 0.0       # length
translateTopographyZ    = 0.0       # length
fluidMinX               = -100.0       # length
fluidMaxX               = 100.0      # length
fluidMinY               = -100.0       # length
fluidMaxY               = 100.0      # length
fluidMinZ               = -100.0       # length
fluidMaxZ               = 100.0       # length
fluidInitVelocityX      = 0.0		# length/time
fluidInitVelocityY      = 0.0		# length/time
fluidInitVelocityZ      = 0.0		# length/time
slipCoefficient         = 0.0		# /
rheologyModel           = NEWTONIAN # either NEWTONIAN, BINGHAM, VOELLMY, MUI, BAGNOLD, or FRICTIONAL
initVisc                = 0.2	    # mass/length/time    -> NEWTONIAN, ALSO MINIMUM FOR FRICTIONAL
plasticVisc             = 0.9		# mass/length/time    -> BINGHAM
yieldStress             = 1.0		# mass/length^2/time  -> BINGHAM
frictionCoefFluid       = 0.8391       # /                   -> FRICTIONAL, VOELLMY, MUI
deltaFriction           = 0.42       # /                   -> MUI
baseInertial            = 0.279       # /                   -> MUI
particleDiameterFluid   = 0.02       # length              -> MUI VOELLMY BAGNOLD
particleDensityFluid    = 1500.0       # mass/length^3       -> MUI VOELLMY BAGNOLD
turbulenceSolver        = 0         # 1 for active       
turbConst               = 0.0256	    # /

# DEM PARAMETERS
particleDensity         = 2600.0	# mass/length^3
contactModel            = LINEAR	# LINEAR OR HERTZIAN
youngMod                = 1.0e8		# mass/length^2/time
poisson                 = 0.3		#
linearStiff             = 0.2e4		# LINEAR
restitution             = 0.88		# / a viscosity coefficient is calculated so that the restitution keeps this value
viscTang                = 0.5		# 0.2
frictionCoefPart        = 0.577		# 0.3
frictionCoefWall        = 0.577		# 0.3
frictionCoefObj         = 0.577		# 0.3
rollingCoefPart         = 0.05		# 0.3
particleFile            = ./null.dat	    #
particleTranslateX      = 0.0		# length
particleTranslateY      = 0.0		# length
particleTranslateZ      = 0.0		# length
particleScale           = 1.0		#
objectFile              = ./null.dat		#
numVisc                 = 0.0001	# mass/length/time -> like dynamic viscosity

# ROTATIONAL REFERENCE FRAME
coriolisSolver          = 0         # trigger Coriolis Acceleration (only DEM)
centrifugalSolver       = 0         # trigger Centrifugal acceleration (only DEM)
rotationX                  = 0.0       # 1/time
rotationY                  = 0.0       # 1/time
rotationZ                  = 0.0       # 1/time
rotationCenterX            = 0.0       # length
rotationCenterY            = 0.0       # length
rotationCenterZ            = 0.0       # length
```

`testWall.yml`

```yml
# Name of the problem (0-1)
name: testWallYML

# If multiple fluid volumes are specified, they are all additive
# Cuboid fluid volumes (0-many)
#fluids_basic:
#    - min: [-50, -50, -50]
#      max: [50, 50, 50]
#    - min: [10, 50, 10]
#      max: [10, 100.5, 10]
# Mathematical expression fluid volumes (0-many)
# Provide an expression that takes any/all (x/y/z)
# Passed the coordinates of a node, it should return
# >0 to denote that a node is fluid
# <=0 to denote that a node is gas
fluids_complex:
    - 5 - sqrt(((x-5)^2) + ((y-5)^2) + ((z-5)^2))
    
    
# Flat walls (0-many)
walls:
    - normal: [1,0,0]
      point: [0.1,0.05,0.05]
      # Remaining properties are optional, and will default to the below values if not specified
      moving: false
      rotational_center: [0,0,0]
      rotational_speed: [0,0,0] # aka angular velocity?
      translation_speed: [0,0,0] # aren't translation vector/speed the the same thing?
      slipping: false
      translating: false
      translation_vector: [0,0,0]
      limited: true
      min: [0.0, 0.0, 0.0] # aka -DBL_MAX
      max: [0.2, 100.0, 1.5] # aka +DBL_MAX
      
# Curved cylinders (0-many)
#cylinders:
#    - point1: [0.1,0.05,0]
#      point2: [0.1,0.05,1.0]
#      radius: 1
#      # Remaining properties are optional, and will default to the below values if not specified
#      moving: false
#      rotational_speed: [0,0,0]
#      slipping: false
#      empty: true # Define whether the cylinder is empty/inner or full/outer
#      translating: false
#      translation_vector: [0,0,0]
#      limited: false
#      min: [-1.79769e+308, -1.79769e+308, -1.79769e+308] # aka -DBL_MAX
#      max: [1.79769e+308, 1.79769e+308, 1.79769e+308] # aka +DBL_MAX

```

</details
